@startuml StateMachine

class PlayerStateMachine extends MonoBehaviour {
	- m_playerController : PlayerController
	- m_currentState : PlayerBaseState
	- m_stateFactory : PlayerStateFactory

	+ setCurrentState(currentState : PlayerBaseState) : PlayerBaseState
	+ getCurrentState() : PlayerBaseState
}

abstract class PlayerBaseState {
	# m_currentContext : PlayerStateMachine
	# m_stateFactory : PlayerStateFactory

	+ PlayerBaseState(PlayerStateMachine currentContext, PlayerStateFactory stateFactory)
	+ {abstract} void EnterState()
	+ {abstract} void UpdateState()
	+ {abstract} void ExitState()
	+ {abstract} void SwitchState(PlayerBaseState newState)
	+ {abstract} void InitSubStates()
}

class PlayerLocationState extends PlayerBaseState {

}

class PlayerIdleState extends PlayerBaseState {

}

class PlayerWalkState extends PlayerBaseState {

}

class PlayerRunState extends PlayerBaseState {

}

class PlayerStateFactory {
	- m_stateMachineContext : PlayerStateMachine

	+ PlayerStateFactory(PlayerStateMachine stateMachineContext)
}

PlayerBaseState --o PlayerStateMachine
PlayerStateFactory --o PlayerStateMachine

@enduml
